name: "Update Tag"
description: "Update the provided tag in the GitHub repo"
author: "Richard Simko"
inputs:
  tag_name:
    description: "Name of the tag to create or update"
    required: true
  tag_ref:
    description: "The target commit or object (branch, tag, etc) to tag"

runs:
  using: "node20"
  main: "dist/main.js"
branding:
  icon: "tag"
  color: "green"
